### ISSUE TITLE
Viele Songs im Classic werden nicht gespielt

### ISSUE THREAD

**Issue by hairmare** [radiorabe/klangbecken#31]

**Comment by hairmare** [comment]
#21 might have a positiv impact on this

**Comment by spameier** [comment]
We should change the [playlist mode](https://www.liquidsoap.info/doc-1.3.7/reference.html#playlist) from `randomize` to `random`:
- `randomize`: shuffle the playlist each time it is loaded, and play it in this order for a whole round
- `random`: pick a random file in the playlist each time

Since we are checking every song when it was last played the danger of repetitions is only there when the onair-state is not correctly signaled to the liquidsoap-script.
