### ISSUE TITLE
Show next playing song

### ISSUE THREAD

**Issue by spameier** [radiorabe/klangbecken#52]
> Und dann wäre noch sehr praktisch, wenn bei der Funktion "play next" zum einen der Track der als nächstes gespielt werden soll irgendwo angezeigt wird und ersetzt wird, wenn bei einem anderen  Track play next gedrück wird.

Need to expand the API (implement GET for `on_play_next`). Part would be adjustements in the UI.

**Comment by hairmare** [comment]
After toying around with the UI in https://github.com/radiorabe/klangbecken-ui/pull/90. I'm realizing that we should also change the behaviour of the liquidsoap script so it only consumes tracks from `prio.m3u` when Klangbecken is on air.

Now, due to Klangbecken always playing tracks, the "next playing" track gets consumed even if Klangbecken is off air.

This leads to a UX where the selected next track just disappears from the UI instead of being the next show opener.

**Comment by smlz** [comment]
This will be closed, as soon as the new UI with the Info page is deployed: https://github.com/radiorabe/klangbecken-ui/pull/190

**Comment by spameier** [comment]
Closed via radiorabe/klangbecken-ui#190
